# Permalinks
permalink:           pretty

# Setup
title:               Collateral Software
tagline:             fschuindt
paginate:            1
baseurl:             https://fschuindt.github.io/blog/
markdown:            kramdown

# Assets
#
# We specify the directory for Jekyll so we can use @imports.
sass:
  sass_dir:          _sass
  style:            :compressed

# About/contact
author:
  name:              Fernando Schuindt
  url:               https://twitter.com/fschuindt
  email:             f.schuindtcs@gmail.com

# Custom vars
version:             2.0.0
github:
  repo:              https://github.com/fschuindt/blog.git

kramdown:
  auto_ids:       true
  footnote_nr:    1
  entity_output:  as_char
  toc_levels:     1..6
  smart_quotes:   lsquo,rsquo,ldquo,rdquo
  input:          GFM
  hard_wrap:      false
  footnote_nr:    1

# Gems
gems:
  - jekyll-paginate
  - jekyll-gist
