# Permalinks
permalink:           pretty

# Setup
title:               Collateral Software
tagline:             fschuindt
paginate:            10
baseurl:             https://fschuindt.github.io/blog

# Assets
#
# We specify the directory for Jekyll so we can use @imports.
sass:
  sass_dir:          _sass
  style:            :compressed

# About/contact
author:
  name:              Fernando Schuindt
  url:               https://twitter.com/fschuindt
  email:             f.schuindtcs@gmail.com

# Custom vars
version:             2.0.0
github:
  repo:              https://github.com/fschuindt/blog.git

# Gems
gems:
  - jekyll-paginate
  - jekyll-gist
